version: "3"

vars:
  IMAGE_NAME: fri-timetable
  IMAGE_LABEL: latest

tasks:
  build:
    cmd: docker build -t "{{.IMAGE_NAME}}:{{.IMAGE_LABEL}}" -f "Dockerfile" .

  run:
    deps:
      - task: build
    cmd: docker-compose -f docker-compose.yml -p {{.IMAGE_NAME}} up --force-recreate --remove-orphans

  deploy:
    deps:
      - task: build
    cmd: docker-compose -f docker-compose.yml -p {{.IMAGE_NAME}} up -d --force-recreate --remove-orphans

  test:
    vars:
      ADDRESS: http://localhost:3000
    cmds:
      - npx lighthouse {{.ADDRESS}} --preset=desktop --view
      - read -p "Press Enter to test mobile" </dev/tty
      - npx lighthouse {{.ADDRESS}} --form-factor mobile --screenEmulation.mobile --view
