import { type TabContent } from "./index";

export const tabDemoContent: TabContent = {  
    degree: [  
      { id: '1', label: 'prva stopnja: univerzitetni', children: [  
        { id: '1-1', label: '1. letnik' },  
        { id: '1-2', label: '2. letnik' },
        { id: '1-2', label: '3. letnik' }
      ] },  
      { id: '2', label: 'prva stopnja: visokošolski', children: [  
        { id: '2-1', label: '1. letnik' },  
        { id: '2-2', label: '2. letnik' },
        { id: '2-2', label: '3. letnik' }
      ] },  
      { id: '3', label: 'druga stopnja: magisterski', children: [  
        { id: '3-1', label: '1. letnik' },  
        { id: '3-2', label: '2. letnik' },
      ] },  
      { id: '4', label: 'tretja stopnja: doktorski', children: [  
        { id: '4-1', label: '1. letnik' },  
        { id: '4-2', label: '2. letnik' },
        { id: '4-3', label: '3. letnik' },
        { id: '4-4', label: '4. letnik' }
      ] },  
    ],  
    teachers: [
      { "id": "1", "label": "Žunkovič, Bojan" },
      { "id": "2", "label": "Fele Žorž, Gašper" },
      { "id": "3", "label": "Rožanc, Igor" },
      { "id": "4", "label": "Mihelič, Jurij" },
      { "id": "5", "label": "Demšar, Jure" },
      { "id": "6", "label": "Modic, David" },
      { "id": "7", "label": "Kunšič, Nina" },
      { "id": "8", "label": "Moškon, Miha" },
      { "id": "9", "label": "Pilipović, Ratko" },
      { "id": "10", "label": "Franetič, Damir" },
      { "id": "11", "label": "Franc, Aleksandra" },
      { "id": "12", "label": "Klisara, Jelena" },
      { "id": "13", "label": "Mesarič Štesl, Daša" },
      { "id": "14", "label": "Fijavž, Gašper" },
      { "id": "15", "label": "Hovelja, Tomaž" },
      { "id": "16", "label": "Vezočnik, Melanija" },
      { "id": "17", "label": "Grohar, Miha" },
      { "id": "18", "label": "Žagar, Aleš" },
      { "id": "19", "label": "Škvorc, Tadej" },
      { "id": "20", "label": "Koloski, Boshko" },
      { "id": "21", "label": "Robnik Šikonja, Marko" },
      { "id": "22", "label": "Batagelj, Borut" },
      { "id": "23", "label": "Solina, Franc" },
      { "id": "24", "label": "Čibej, Uroš" },
      { "id": "25", "label": "Fürst, Luka" },
      { "id": "26", "label": "Čehovin Zajc, Luka" },
      { "id": "27", "label": "Bohak, Ciril" },
      { "id": "28", "label": "Huč, Aleks" },
      { "id": "29", "label": "Brodnik, Andrej" },
      { "id": "30", "label": "Špetič, Aleš" },
      { "id": "31", "label": "Bosnić, Zoran" },
      { "id": "32", "label": "Hvala, Aljaž" },
      { "id": "33", "label": "Klanjšček, Klemen" },
      { "id": "34", "label": "Jager, Franc" },
      { "id": "35", "label": "Nabergoj, David" },
      { "id": "36", "label": "Teran, Simon" },
      { "id": "37", "label": "Pejović, Veljko" },
      { "id": "38", "label": "Pesek, Matevž" },
      { "id": "39", "label": "Meden, Blaž" },
      { "id": "40", "label": "PELHAN, Jer" },
      { "id": "41", "label": "ŠPENDL, Martin" },
      { "id": "42", "label": "Poličar, Pavlin Gregor" },
      { "id": "43", "label": "Kokošar, Jaka" },
      { "id": "44", "label": "Zupan, Blaž" },
      { "id": "45", "label": "Curk, Tomaž" },
      { "id": "46", "label": "Žitnik, Slavko" },
      { "id": "47", "label": "Dobrevski, Matej" },
      { "id": "48", "label": "Kochovski, Petar" },
      { "id": "49", "label": "Gomišček, Rok" },
      { "id": "50", "label": "Stankovski, Vlado" },
      { "id": "51", "label": "Lavbič, Dejan" },
      { "id": "52", "label": "Jelenc, David" },
      { "id": "53", "label": "Šter, Branko" },
      { "id": "54", "label": "Sadikov, Aleksander" },
      { "id": "55", "label": "Faganeli Pucer, Jana" },
      { "id": "56", "label": "Muhovič, Jon" },
      { "id": "57", "label": "Veljković, Kristina" },
      { "id": "58", "label": "Kink, Peter Marijan" },
      { "id": "59", "label": "Češnovar, Rok" },
      { "id": "60", "label": "Bulić, Patricio" },
      { "id": "61", "label": "Sluga, Davor" },
      { "id": "62", "label": "Skočaj, Danijel" },
      { "id": "63", "label": "Hočevar, Tomaž" },
      { "id": "64", "label": "Lesar, Žiga" },
      { "id": "65", "label": "rezervirano, rezervirano" },
      { "id": "66", "label": "Pušnik, Žiga" },
      { "id": "67", "label": "Lazar, Timotej" },
      { "id": "68", "label": "Groznik, Vida" },
      { "id": "69", "label": "PROSTO, PROSTO" }
    ],
    classrooms: [
      { "id": "1", "label": "PR10" },
      { "id": "2", "label": "PR11" },
      { "id": "3", "label": "PR12" },
      { "id": "4", "label": "PR09" },
      { "id": "5", "label": "PR15" },
      { "id": "6", "label": "PR05" },
      { "id": "7", "label": "PR17" },
      { "id": "8", "label": "PR16" },
      { "id": "9", "label": "PR06" },
      { "id": "10", "label": "PR07" },
      { "id": "11", "label": "PR08" },
      { "id": "12", "label": "PR14" },
      { "id": "13", "label": "P22" },
      { "id": "14", "label": "P02" },
      { "id": "15", "label": "P01" },
      { "id": "16", "label": "P04" },
      { "id": "17", "label": "P03" },
      { "id": "18", "label": "PA" },
      { "id": "19", "label": "P20" },
      { "id": "20", "label": "P19" },
      { "id": "21", "label": "P18" },
      { "id": "22", "label": "P21" },
      { "id": "23", "label": "R2.38" },
      { "id": "24", "label": "Velika fizikalna predavalnica" },
      { "id": "25", "label": "Frižider" },
      { "id": "26", "label": "Na daljavo" }
    ],
    subjects: [
      { "id": "1", "label": "Algoritmi in podatkovne strukture 1" },
      { "id": "2", "label": "Bayesova statistika" },
      { "id": "3", "label": "Človeški vidiki varnosti" },
      { "id": "4", "label": "Digitalna vezja" },
      { "id": "5", "label": "Digitalno načrtovanje" },
      { "id": "6", "label": "Diskretne strukture" },
      { "id": "7", "label": "Ekonomika in podjetništvo" },
      { "id": "8", "label": "Elektronsko in mobilno poslovanje" },
      { "id": "9", "label": "Elektronsko poslovanje" },
      { "id": "10", "label": "Fizika" },
      { "id": "11", "label": "Funkcijsko programiranje" },
      { "id": "12", "label": "Grafično oblikovanje" },
      { "id": "13", "label": "Informacijska varnost in zasebnost" },
      { "id": "14", "label": "Informacijski sistemi" },
      { "id": "15", "label": "Inteligentni sistemi" },
      { "id": "16", "label": "Interaktivnost in oblikovanje informacij" },
      { "id": "17", "label": "Izračunljivost in računska zahtevnost" },
      { "id": "18", "label": "Komunikacija človek računalnik" },
      { "id": "19", "label": "Komunikacijski protokoli in omrežna varnost" },
      { "id": "20", "label": "Kriptografija in računalniška varnost" },
      { "id": "21", "label": "Matematika" },
      { "id": "22", "label": "Matematika 1" },
      { "id": "23", "label": "Mobilno zaznavanje" },
      { "id": "24", "label": "Modeliranje računalniških omrežij" },
      { "id": "25", "label": "Multimedijske tehnologije" },
      { "id": "26", "label": "Multimedijski sistemi" },
      { "id": "27", "label": "Načela negotovosti" },
      { "id": "28", "label": "Napredne metode strojnega učenja" },
      { "id": "29", "label": "Nekonvencionalne platforme in metode procesiranja" },
      { "id": "30", "label": "Numerične metode" },
      { "id": "31", "label": "Obdelava biomedicinskih signalov in slik" },
      { "id": "32", "label": "Odločitveni sistemi" },
      { "id": "33", "label": "Organizacija računalnikov" },
      { "id": "34", "label": "Organizacija računalniških sistemov" },
      { "id": "35", "label": "Osnove digitalnih vezij" },
      { "id": "36", "label": "Osnove matematične analize" },
      { "id": "37", "label": "Osnove podatkovnih baz" },
      { "id": "38", "label": "Osnove programiranja (FKKT)" },
      { "id": "39", "label": "Osnove umetne inteligence" },
      { "id": "40", "label": "Planiranje in upravljanje informatike" },
      { "id": "41", "label": "Podatkovne baze 2" },
      { "id": "42", "label": "Porazdeljeni sistemi" },
      { "id": "43", "label": "Postopki razvoja programske opreme" },
      { "id": "44", "label": "Procesna avtomatika" },
      { "id": "45", "label": "Programiranje 1" },
      { "id": "46", "label": "Programiranje energijsko omejenih naprav" },
      { "id": "47", "label": "Računalniška arhitektura" },
      { "id": "48", "label": "Računalniška grafika" },
      { "id": "49", "label": "Računalniška grafika in tehnologija iger" },
      { "id": "50", "label": "Računalniška podpora oblikovanju I (ALUO)" },
      { "id": "51", "label": "Računalniška zvočna produkcija" },
      { "id": "52", "label": "Računalniške storitve v oblaku" },
      { "id": "53", "label": "Robotika in računalniško zaznavanje" },
      { "id": "54", "label": "Sistemska programska oprema" },
      { "id": "55", "label": "Skupinsko vedenje" },
      { "id": "56", "label": "Slikovna biometrija" },
      { "id": "57", "label": "Spletno programiranje" },
      { "id": "58", "label": "Strojno učenje" },
      { "id": "59", "label": "Strojno učenje za podatkovne vede 2" },
      { "id": "60", "label": "Tehnične veščine" },
      { "id": "61", "label": "Tehnologija iger in navidezna resničnost" },
      { "id": "62", "label": "Tehnologija programske opreme" },
      { "id": "63", "label": "Tehnologija upravljanja podatkov" },
      { "id": "64", "label": "Topološka analiza podatkov" },
      { "id": "65", "label": "Umetna inteligenca" },
      { "id": "66", "label": "Umetno zaznavanje" },
      { "id": "67", "label": "Uvod v bioinformatiko" },
      { "id": "68", "label": "Uvod v podatkovne vede" },
      { "id": "69", "label": "Uvod v računalništvo" },
      { "id": "70", "label": "Varnost komunikacij in zaščita vsebin" },
      { "id": "71", "label": "Varnost organizacij" },
      { "id": "72", "label": "Varnost podatkov" },
      { "id": "73", "label": "Varnost sistemov" },
      { "id": "74", "label": "Verjetnost in statistika" },
      { "id": "75", "label": "Veščine v znanstvenem delu 1" },
      { "id": "76", "label": "Veščine v znanstvenem delu II" },
      { "id": "77", "label": "Vgrajeni sistemi" },
      { "id": "78", "label": "Vzporedni in porazdeljeni sistemi in algoritmi" },
      { "id": "79", "label": "Seminar 1 in Seminar 3" },
      { "id": "80", "label": "Izbrana poglavja iz umetne inteligence 1 (Veliki jezikovni modeli s perspektive strojnega učenja)" }
    ]
  };  